HAN-7: Implementar conexión con RabbitMQ y envío de paquetes
Hanagotchi/simulator pull request #5
Opened 2024-01-19 22:51 UTC by violetaperezandrade

2024-01-22 20:42 UTC, Agustinefe requested changes
Tenemos que comenzar a documentar los .env, para no tener que estar buscando en el codigo si agregamos una variable nueva. ¿Podrias documentar este .env en el readme?

2024-01-22 20:42 UTC, Agustinefe commented on src/main.py
> +            middleware.send_message("device_plant", json.dumps(current_packet))
El nombre de la queue deberia pasarse como variable de entorno. Por otra parte, tal vez deberiamos llamar "measurements" a la queue, porque lo que transporta son mediciones.

2024-01-30 01:34 UTC, violetaperezandrade commented on src/main.py
> +            middleware.send_message("device_plant", json.dumps(current_packet))
yes, en este caso en particular tiene que coincidir con el nombre seteado en el servicio de mediciones. Agregado el nombre como variable de entorno y documentado el .env

2024-01-30 20:13 UTC, Agustinefe approved these changes

2024-01-31 03:04 UTC, feijooso approved these changes
LGTM

2024-01-31 12:38 UTC, merged